server:
  port: 8762
spring:
  application:
    name: health-handler-provider
eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
    hostname: ${spring.cloud.client.ip-address}
    # 发送心跳间隔
    lease-renewal-interval-in-seconds: 30
    # 清理实例期限
    lease-expiration-duration-in-seconds: 90
  client:
    service-url:
      defaultZone: http://192.168.1.136:8761/eureka/
    instance-info-replication-interval-seconds: 10
