server:
  port: 8761
spring:
  application:
    name: first-cloud-server
  profiles: slave1
eureka:
  instance:
    hostname: slave1
  client:
    serviceUrl:
      defaultZone: http://slave2:8762/eureka/
  server:
    # 关闭注册中心的自我保护机制，防止已关闭的实例无法从注册中心剔除，服务关闭后up依然显示，开发环境下建议关闭。
    enable-self-preservation: false
---
server:
  port: 8762
spring:
  application:
    name: first-cloud-server
  profiles: slave2
eureka:
  instance:
    hostname: slave2
  client:
    serviceUrl:
      defaultZone: http://slave1:8761/eureka/
  server:
    # 关闭注册中心的自我保护机制，防止已关闭的实例无法从注册中心剔除，服务关闭后up依然显示，开发环境下建议关闭。
    enable-self-preservation: false