server:
  port: 8761
spring:
  application:
    name: eurka-server
  security:
    user:
      name: admin
      password: admin
#  profiles: slave1
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/
    register-with-eureka: false
    fetch-registry: false
  server:
    # 关闭注册中心的自我保护机制，防止已关闭的实例无法从注册中心剔除，服务关闭后up依然显示，开发环境下建议关闭。
    enable-self-preservation: false
---
#server:
#  port: 8762
#spring:
#  application:
#    name: first-cloud-server
#  profiles: slave2
#eureka:
#  instance:
#    hostname: slave2
#  client:
#    serviceUrl:
#      defaultZone: http://slave1:8761/eureka/
#  server:
#    # 关闭注册中心的自我保护机制，防止已关闭的实例无法从注册中心剔除，服务关闭后up依然显示，开发环境下建议关闭。
#    enable-self-preservation: false