server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    # 是否将自己的信息注册到Eureka服务器，默认值为true
    registerWithEureka: false
    # 是否到Eureka服务器中抓取注册信息
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    # 关闭注册中心的自我保护机制，防止已关闭的实例无法从注册中心剔除，服务关闭后up依然显示，开发环境下建议关闭。
    enable-self-preservation: false
    # 定时清理表实例，单位应该是毫秒（猜测……）
    eviction-interval-timer-in-ms: 60000
spring:
  application:
    name: eurka-server